### ISSUE TITLE
not able to install via pip

### ISSUE THREAD

**Issue by Yneth** [woodruffw/pyrage#13]
```
pip install pyrage
ERROR: Could not find a version that satisfies the requirement pyrage (from versions: none)
ERROR: No matching distribution found for pyrage
```

```
pip install https://pypi.org/project/pyrage/
Collecting https://pypi.org/project/pyrage/
  Using cached https://pypi.org/project/pyrage/ (65 kB)
  ERROR: Cannot unpack file /private/var/folders/5p/rnr_sg3n0hd_q7j_wb13t8h00000gn/T/pip-unpack-svpz01ub/pyrage (downloaded from /private/var/folders/5p/rnr_sg3n0hd_q7j_wb13t8h00000gn/T/pip-req-build-bkq2kcp6, content-type: text/html; charset=UTF-8); cannot detect archive format
ERROR: Cannot determine archive format of /private/var/folders/5p/rnr_sg3n0hd_q7j_wb13t8h00000gn/T/pip-req-build-bkq2kcp6
```

macos big sur 11.6.6
python 3.7.13

**Comment by woodruffw** [comment]
Thanks for the report.

Looks like I forgot to publish macOS wheels; I'll fix that tonight or tomorrow.

**Comment by woodruffw** [comment]
Sorry for the delay here -- it turned out to be a little more involved (I need to refactor the publishing action more extensively). Should be done soon, and I'll comment again here when a new stable release is available.

**Comment by woodruffw** [comment]
Okay, I've cut `v1.0.1` and it should be on PyPI shortly with macOS wheels. Please let me know if you have any problems with them.

**Comment by Gunni** [comment]
Still broken for me.

Windows 10 amd64.
Python 3.10.2

**Comment by woodruffw** [comment]
Yeah, I don't currently publish any Windows wheels at all -- it's not something I've looked closely into. I'll give it a try this weekend, though.

**Comment by woodruffw** [comment]
Opened #15 to track that.
