### ISSUE TITLE
Publish Windows wheels

### ISSUE THREAD

**Issue by woodruffw** [woodruffw/pyrage#15]
I have no idea how this works, but hopefully it won't be too hard in CI.

See #13.

**Comment by balu-** [comment]
any progress?

**Comment by woodruffw** [comment]
Not yet, it popped off my stack. I'll probably give it a stab sometime this week, but in the meantime I'm happy to review anybody else's attempts.

**Comment by liujuanjuan1984** [comment]
Thank u for your pyrage.

It took me  about an hour to  try to install pyrage with my windows computer which always returned got  no version. Now I know the reason. 

Lucky, I tried to install pyrage with my linux server and it works well.

Wish that Windows wheels will be published.

**Comment by woodruffw** [comment]
Thanks for letting me know. Again: if someone would like to try their hand at this, I'm happy to review a PR. Otherwise, it's on my long list of things to do 🙂

**Comment by woodruffw** [comment]
Figured this out. Starting with `1.0.2`, all pyrage releases should also have Windows wheels.

**Comment by woodruffw** [comment]
Wheels are published, let me know if you run into any problems.

**Comment by liujuanjuan1984** [comment]
> Figured this out. Starting with `1.0.2`, all pyrage releases should also have Windows wheels.

Thank u. It works.

```log
C:\Users\User>pip install pyrage
Collecting pyrage
  Downloading pyrage-1.0.2-cp37-abi3-win_amd64.whl (544 kB)
     ---------------------------------------- 544.2/544.2 kB 502.8 kB/s eta 0:00:00
Installing collected packages: pyrage
Successfully installed pyrage-1.0.2
```
