### ISSUE TITLE
Consider providing a `Cargo.lock`

### ISSUE THREAD

**Issue by vikanezrimaya** [woodruffw/pyrage#54]
Current Rust best practices recommend committing `Cargo.lock` even for libraries: https://blog.rust-lang.org/2023/08/29/committing-lockfiles.html

Additionally, this makes downstream packaging easier in some places, like [nixpkgs](https://github.com/nixos/nixpkgs), where a Cargo.lock is mandatory for Rust packages.

Since this package is likely to be consumed by non-Rust sources, providing a `Cargo.lock` feels sensible even under old guidelines.

**Comment by woodruffw** [comment]
This is something I was not super clear on: `pyrage` is meant to be exposed only as a Python library, so I wasn't sure if checking the `Cargo.lock` file into the repo meant sense. Everything you've said sounds reasonable, though, so I'll add it when I have time.
