### ISSUE TITLE
Support age plugins

### ISSUE THREAD

**Issue by vikanezrimaya** [woodruffw/pyrage#55]
Spec: https://c2sp.org/age-plugin

The `rage` CLI implements plugins, so why shouldn't this tool?

Documentation for `rage`'s API for plugin usage: https://docs.rs/age/0.9.2/age/plugin/index.html

I may or may not want to try my hand at implementing this.

**Comment by woodruffw** [comment]
Please do! I'd be happy to review API bindings for plugins.

(If you have outstanding thoughts before beginning, I'm happy to discuss them as well. But I think this should be pretty straightforward, like the "baked in" identity types are.)
